version: 2

python:
   version: 3.6
   system_packages: true
   install:
      - requirements: docs/rtd-requirements.txt
      - requirements: docs/requirements.txt
      - method: pip
        path: .
