name: black
on:
  workflow_dispatch:
  schedule:
    - cron: "10 9 * * *"

jobs:
  format:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install black
        run: pip install black
      - name: Black
        run: black --check manim tests example_scenes
      - name: Print Black Version if Failed
        if: ${{ failure() }}
        id: black-check
        run: |
          $env:GITHUB_TOKEN = $env:access_token
          $blackVer = black --version
          $blackVersion = python -c "print('$($blackVer)'.split()[2])"
          $date = python -c "import time;print(time.localtime().tm_mday)"
          $pushBranch="black-update-$($blackVersion)-$($date)"
          git checkout -b $pushBranch "origin/master"
          black manim
          black tests
          black example_scenes
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Running Black ON Master"
          echo "pushing origin"
          git push origin "$($pushBranch)" --force
      - name: Make a PR
        if: failure()
        env:
          access_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $env:GITHUB_TOKEN = $env:access_token
          $blackVer = black --version
          $blackVersion = python -c "print('$($blackVer)'.split()[2])"
          $date = python -c "import time;print(time.localtime().tm_mday)"
          $pushBranch="black-update-$($blackVersion)-$($date)"
          $postContents = @{title="Black on Master - Automation";head="$($pushBranch)";base="master"} | ConvertTo-Json -Compress
          Invoke-WebRequest `
            -Method POST `
            -Headers @{ "Accept" = "application/vnd.github.v3+json"; "Authorization"= "token $($env:access_token)"}  `
            -Uri https://api.github.com/repos/naveen521kk/manim/pulls `
            -Body "$($postContents)"
          #gh pr create --title "Black on Master - Automation" --body "The current black version is $($blackVersion)" 
