name: black
on:
  workflow_dispatch:
  schedule:
    - cron: "10 9 * * *"

jobs:
  format:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install black
        run: pip install black
      - name: Black
        run: black --check manim tests example_scenes
      - name: Print Black Version if Failed
        if: ${{ failure() }}
        env:
          access_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $env:GITHUB_TOKEN = $env:access_token
          $blackVersion = Get-Version $(black --version)
          git checkout -b "black-update-$($blackVersion)" "origin/master"
          black manim
          black tests
          black example_scenes
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Running Black ON Master"
          git push -u "origin/black-update-$($blackVersion)"
          gh pr create --title "Black on Master - Automation" --body "The current black version is $($blackVersion)" 
