name: black
on:
  workflow_dispatch:
  schedule:
    - cron: "10 9 * * *"

jobs:
  format:
    runs-on: windows-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install black
        run: pip install black
        
      - name: Print Black Version if Failed
        if: ${{ failure() }}
        run: |
          try {
          black --check --diff manim
          black --check --diff tests
          black --check --diff example_scenes}
          catch {
          $blackVersion = pip freeze | Select-String -Pattern "black"
          git checkout -b "black-update-$($blackVersion)" "origin/master"
          black manim
          black tests
          black example_scenes
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Running Black ON Master"
          git push -u "black-update-$($blackVersion)"
          gh pr create --title "Black on Master - Automation" --body "The current black version is $($blackVersion)"}
